name: sk
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/sk/assets/images/ellipse63.png
    - packages/sk/assets/images/vector.svg
    - packages/sk/assets/images/ellipse62.png
    - packages/sk/assets/images/icbaselinemobilescreenshare.svg
    - packages/sk/assets/images/ellipse64.png
    - packages/sk/assets/images/rectangle1958.png
    - packages/sk/assets/images/ellipse147.png
    - packages/sk/assets/images/ellipse148.png
    - packages/sk/assets/images/ellipse149.png
    - packages/sk/assets/images/ellipse150.png
    - packages/sk/assets/images/ellipse151.png
    - packages/sk/assets/images/rectangle1952.png
    - packages/sk/assets/images/rectangle1953.png
    - packages/sk/assets/images/rectangle1954.png
    - packages/sk/assets/images/rectangle1955.png
    - packages/sk/assets/images/rectangle1956.png
    - packages/sk/assets/images/rectangle1894.png
    - packages/sk/assets/images/rectangle1895.png
    - packages/sk/assets/images/rectangle1896.png
    - packages/sk/assets/images/rectangle1914.svg
    - packages/sk/assets/images/image262.png
    - packages/sk/assets/images/rectangle1912.png
    - packages/sk/assets/images/rectangle1918.png
    - packages/sk/assets/images/image271.png
    - packages/sk/assets/images/image273.png
    - packages/sk/assets/images/image272.png
    - packages/sk/assets/images/image275.png
    - packages/sk/assets/images/image266.png
    - packages/sk/assets/images/image268.png
    - packages/sk/assets/images/image276.png
    - packages/sk/assets/images/image277.png
    - packages/sk/assets/images/image279.png
    - packages/sk/assets/images/rectangle1916.png
    - packages/sk/assets/images/image263.png
    - packages/sk/assets/images/ellipse144.png
    - packages/sk/assets/images/fasolidlock.svg
    - packages/sk/assets/images/bxstimefive.svg
    - packages/sk/assets/images/rectangle1927.png
    - packages/sk/assets/images/ellipse145.png
    - packages/sk/assets/images/image265.png
