name: saa
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/saa/assets/images/ellipse62.png
    - packages/saa/assets/images/icbaselinemobilescreenshare.svg
    - packages/saa/assets/images/vector.svg
    - packages/saa/assets/images/ellipse64.png
    - packages/saa/assets/images/rectangle1958.png
    - packages/saa/assets/images/ellipse63.png
    - packages/saa/assets/images/ellipse147.png
    - packages/saa/assets/images/ellipse148.png
    - packages/saa/assets/images/ellipse149.png
    - packages/saa/assets/images/ellipse150.png
    - packages/saa/assets/images/ellipse151.png
    - packages/saa/assets/images/rectangle1952.png
    - packages/saa/assets/images/rectangle1953.png
    - packages/saa/assets/images/rectangle1954.png
    - packages/saa/assets/images/rectangle1955.png
    - packages/saa/assets/images/rectangle1956.png
    - packages/saa/assets/images/image278.png
    - packages/saa/assets/images/image279.png
    - packages/saa/assets/images/image280.png
    - packages/saa/assets/images/image281.png
    - packages/saa/assets/images/rectangle1912.png
    - packages/saa/assets/images/rectangle1918.png
    - packages/saa/assets/images/image271.png
    - packages/saa/assets/images/image273.png
    - packages/saa/assets/images/image272.png
    - packages/saa/assets/images/image275.png
    - packages/saa/assets/images/rectangle1916.png
    - packages/saa/assets/images/image263.png
    - packages/saa/assets/images/ellipse144.png
    - packages/saa/assets/images/fasolidlock.svg
    - packages/saa/assets/images/bxstimefive.svg
    - packages/saa/assets/images/rectangle1927.png
    - packages/saa/assets/images/ellipse145.png
    - packages/saa/assets/images/image265.png
    - packages/saa/assets/images/profile.png
